#!/usr/bin/env node
'use strict';

const http   = require('http');
const fs     = require('fs');
const path   = require('path');
const os     = require('os');
const crypto = require('crypto');

// ─── Port resolution ─────────────────────────────────────────────────────────
const cliPort = parseInt(process.argv[2] || '', 10);
const PORT    = (!isNaN(cliPort) && cliPort > 0 && cliPort < 65536)
                ? cliPort
                : parseInt(process.env.PORT || '8093', 10);

const { html: HTML_CONTENT, config: CONFIG } = require('./_bundle'); // auto-generated by build.js — not a taint source
const NVD_CVE_URL  = 'https://services.nvd.nist.gov/rest/json/cves/2.0';
const LOG_DIR     = path.join(__dirname, 'logs');


// ─── Load .env.local (API key only — sensitive, never sent to browser) ───────
function loadEnv(filePath) {
    const env = {};
    try {
        for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
            const t = line.trim();
            if (!t || t.startsWith('#')) continue;
            const eq = t.indexOf('=');
            if (eq < 0) continue;
            env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
        }
    } catch { /* .env.local not found — skip */ }
    return env;
}

const env              = loadEnv(path.join(__dirname, '.env.local'));
const defaultApiKey    = env.NIST_API_KEY || '';

// Non-sensitive config comes from config-bundle (require, not fs.readFile)
const defaultWhitelist = CONFIG.whitelist;
const REQUEST_DELAY    = CONFIG.requestDelay;
const portableEnable   = CONFIG.portableEnable;
const defaultPortables = CONFIG.portables;

// ─── Daily-rolling logger ─────────────────────────────────────────────────────
fs.mkdirSync(LOG_DIR, { recursive: true });

let _logStream = null;
let _logDate   = '';

function _logDateStr() {
    const d = new Date();
    return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
}

function _logTs() {
    const d   = new Date();
    const ymd = _logDateStr();
    const hh  = String(d.getHours()).padStart(2, '0');
    const mm  = String(d.getMinutes()).padStart(2, '0');
    const ss  = String(d.getSeconds()).padStart(2, '0');
    const ms  = String(d.getMilliseconds()).padStart(3, '0');
    return `${ymd} ${hh}${mm}${ss}${ms}`;
}

function _getStream() {
    const today = _logDateStr();
    if (today !== _logDate) {
        try { _logStream?.end(); } catch (_) {}
        _logStream = fs.createWriteStream(
            path.join(LOG_DIR, `server_${today}.log`), { flags: 'a' }
        );
        _logDate = today;
    }
    return _logStream;
}

function slog(sid, msg) {
    const line = `${sid}: ${_logTs()} ${msg}`;
    console.log(line);
    try { _getStream().write(line + '\n'); } catch (_) {}
}

// ─── Session ID ───────────────────────────────────────────────────────────────
let _sessionSeq = 0;
const newSid = () => `#${String((_sessionSeq = _sessionSeq % 9999 + 1)).padStart(4, '0')}`;

// ─── Global NVD rate-limit queue ─────────────────────────────────────────────
// All concurrent sessions share this queue so combined request rate never
// exceeds REQUEST_DELAY regardless of how many users scan simultaneously.
let _nvdLastAt = 0;
let _nvdQueue  = Promise.resolve();

function nvdSlot() {
    const p = _nvdQueue.then(() => {
        const wait = Math.max(0, _nvdLastAt + REQUEST_DELAY - Date.now());
        return sleep(wait).then(() => { _nvdLastAt = Date.now(); });
    });
    _nvdQueue = p.catch(() => {});
    return p;
}

// ─── Page injection ───────────────────────────────────────────────────────────
// Injected before </body>: signals proxy mode and pre-fills settings.
// jsStr: JSON.stringify + escape </ so it cannot terminate the <script> block.
const jsStr = v => JSON.stringify(v).replace(/<\//g, '\\u003C/');
const injectLines = [
    `window.__NVD_PROXY__       = '/api/scan';`,
    `window.__NVD_DELAY__       = ${REQUEST_DELAY};`,
    `window.__PORTABLE_ENABLE__ = ${portableEnable};`,
];
if (portableEnable) {
    for (const p of defaultPortables) {
        injectLines.push(`if(typeof addPortableRow==='function')addPortableRow(${jsStr(p.name)},${jsStr(p.version)});`);
    }
} else {
    injectLines.push(`var _ps=document.getElementById('portable-section');if(_ps)_ps.style.display='none';`);
}
if (defaultWhitelist) {
    injectLines.push(
        `var w=document.getElementById('whitelist'); if(w&&!w.value)w.value=${jsStr(defaultWhitelist)};`
    );
}
if (defaultApiKey) {
    injectLines.push(
        `var fg=document.getElementById('api-key')?.closest('.form-group');`,
        `if(fg){fg.style.display='none';var el=document.createElement('div');el.className='form-group';el.innerHTML='<label>NIST API Key</label><span class="hint" style="color:#4ade80">&#10003; 由伺服器代理處理（.env.local）</span>';fg.parentNode.insertBefore(el,fg);}`
    );
}
const makeInjectScript = n =>
    `<script nonce="${n}">(function(){\n  ${injectLines.join('\n  ')}\n})();</script>`;

// ─── Helpers ─────────────────────────────────────────────────────────────────
const sleep    = ms => new Promise(r => setTimeout(r, ms));
const readBody = req => new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', c => chunks.push(c));
    req.on('end',  () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
});

// ─── POST /api/scan ───────────────────────────────────────────────────────────
// Accepts { keywords: string[], maxCves: number, meta: object }.
// Streams NDJSON: one {"keyword","data"} line per item, then {"done":true}.
async function scanHandler(req, res) {
    const sid = newSid();
    const ip  = req.socket.remoteAddress || '?';

    let keywords, maxCves, meta;
    try {
        const body = await readBody(req);
        const parsed = JSON.parse(body);
        keywords = parsed.keywords;
        maxCves  = Math.max(1, parseInt(parsed.maxCves, 10) || 50);
        meta     = parsed.meta || {};
        if (!Array.isArray(keywords) || keywords.length === 0)
            throw new Error('keywords must be a non-empty array');
    } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
        return;
    }

    // ── Log scan start ────────────────────────────────────────────────────────
    const total      = keywords.length;
    const portable   = meta.portableCount    || 0;
    const wl         = meta.whitelistedCount || 0;
    const skipped    = meta.skippedCount     || 0;
    const dedup      = meta.dedupCount       || 0;
    const minSev      = meta.minSeverity      || '?';
    const minYear     = meta.minYear && meta.minYear !== '?' ? Number(meta.minYear) : 0;
    const apiKeyTag   = defaultApiKey ? '已設定' : '未設定';
    const estSecs     = Math.ceil(total * REQUEST_DELAY / 1000);
    const portableTag = portable ? ` + ${portable} Portable` : '';
    const yearTag     = minYear ? String(minYear) : '不限';

    slog(sid, `▶ [${ip}] 開始掃描 ${total} 項軟體${portableTag} (白名單:${wl} 子元件:${skipped} 去重:${dedup})`);
    slog(sid, `  設定：嚴重度≥${minSev}，年份≥${yearTag}，每項最多${maxCves}筆，API Key:${apiKeyTag}，預估${estSecs}秒`);

    let cancelled = false;
    req.on('close', () => { cancelled = true; });
    res.on('error', () => {});

    res.writeHead(200, {
        'Content-Type':           'application/x-ndjson',
        'Cache-Control':          'no-cache',
        'X-Accel-Buffering':      'no',
        'X-Content-Type-Options': 'nosniff',
    });
    res.write(JSON.stringify({ sid }) + '\n');

    const reqHeaders = { 'User-Agent': 'CVE-Web-Scanner/1.0' };
    if (defaultApiKey) reqHeaders['apiKey'] = defaultApiKey;

    let scanned = 0;
    for (let i = 0; i < keywords.length; i++) {
        if (cancelled) break;

        await nvdSlot();
        if (cancelled) break;

        const keyword = keywords[i];
        scanned++;

        const params = new URLSearchParams({
            keywordSearch:  keyword,
            resultsPerPage: String(maxCves),
            noRejected:     '',
        });
        const url = `${NVD_CVE_URL}?${params}`;

        try {
            let nvdRes;
            try {
                nvdRes = await fetch(url, { headers: reqHeaders, signal: AbortSignal.timeout(30000) });
            } catch (firstErr) {
                if (firstErr.name === 'AbortError') throw firstErr;
                slog(sid, `  [${scanned}/${total}] ${keyword} — TypeError，重試`);
                nvdRes = await fetch(url, { headers: reqHeaders, signal: AbortSignal.timeout(30000) });
            }

            if (nvdRes.status === 429) {
                slog(sid, `  [${scanned}/${total}] ${keyword} — 429 Rate Limit，等待15秒`);
                await sleep(15000);
                if (cancelled) break;
                nvdRes = await fetch(url, { headers: reqHeaders, signal: AbortSignal.timeout(30000) });
            }

            if (!nvdRes.ok) {
                const text = await nvdRes.text().catch(() => '');
                throw new Error(`HTTP ${nvdRes.status}${text ? ': ' + text.slice(0, 120) : ''}`);
            }

            const data      = await nvdRes.json();
            const nvdTotal  = data.totalResults ?? 0;
            const returned  = data.vulnerabilities?.length ?? 0;
            const extra = nvdTotal > returned ? `(取前${returned}筆)` : '';
            slog(sid, `  [${scanned}/${total}] ${keyword} — 從NVD共取回${nvdTotal}筆${extra}，(尚未過濾嚴重度/年份/關聯性)`);
            res.write(JSON.stringify({ keyword, data }) + '\n');

        } catch (err) {
            if (err.name === 'AbortError') break;
            slog(sid, `  [${scanned}/${total}] ${keyword} — 失敗：${err.message}`);
            res.write(JSON.stringify({ keyword, error: err.message }) + '\n');
        }
    }

    if (cancelled) {
        slog(sid, `■ [${ip}] 掃描取消（已完成 ${scanned}/${total}）`);
    } else {
        slog(sid, `✓ [${ip}] 掃描完成 ${scanned}/${total}`);
    }

    if (!cancelled) res.write(JSON.stringify({ done: true }) + '\n');
    res.end();
}

// ─── Request handler ──────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
    if (req.url === '/api/log' && req.method === 'POST') {
        readBody(req).then(body => {
            try {
                const { sid, msg } = JSON.parse(body);
                if (sid && msg) {
                    for (const line of String(msg).split('\n'))
                        slog(sid, `  ${line}`);
                }
            } catch (_) {}
            res.writeHead(204); res.end();
        }).catch(() => { res.writeHead(400); res.end(); });
        return;
    }

    if (req.url === '/api/scan' && req.method === 'POST') {
        scanHandler(req, res).catch(err => {
            console.error('[scan] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.method !== 'GET') {
        res.writeHead(405, { 'X-Content-Type-Options': 'nosniff' }); res.end(); return;
    }


    if (req.url !== '/' && req.url !== '/index.html') {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' });
        res.end('404 Not Found');
        return;
    }

    const nonce  = crypto.randomBytes(16).toString('base64');
    const nonced = HTML_CONTENT.replace(/(<script)(?=[\s>])/i, `$1 nonce="${nonce}"`);
    const idx    = nonced.lastIndexOf('</body>');
    const html   = nonced.slice(0, idx) + makeInjectScript(nonce) + '\n' + nonced.slice(idx);
    const buf    = Buffer.from(html, 'utf8');
    const csp    = [
        "default-src 'self'",
        `script-src 'nonce-${nonce}'`,
        "style-src 'self' 'unsafe-inline'",
        "connect-src 'self' https://services.nvd.nist.gov",
        "img-src 'self' data: blob:",
        "object-src 'none'",
        "base-uri 'self'",
    ].join('; ');
    res.writeHead(200, {
        'Content-Type':            'text/html; charset=utf-8',
        'Cache-Control':           'no-store',
        'Content-Length':          buf.length,
        'X-Content-Type-Options':  'nosniff',
        'Content-Security-Policy': csp,
    });
    res.end(buf);
});

// ─── Start ────────────────────────────────────────────────────────────────────
server.keepAliveTimeout = 65000;
server.headersTimeout   = 70000;

server.listen(PORT, '0.0.0.0', () => {
    const c = { bold: '\x1b[1m', reset: '\x1b[0m', cyan: '\x1b[36m', green: '\x1b[32m', gray: '\x1b[90m' };

    console.log(`\n${c.bold}CVE Web Scanner${c.reset}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}本機：${c.reset}    ${c.cyan}http://localhost:${PORT}${c.reset}`);

    for (const addrs of Object.values(os.networkInterfaces())) {
        for (const addr of addrs) {
            if (addr.family === 'IPv4' && !addr.internal) {
                console.log(`${c.gray}區域網路：${c.reset} ${c.bold}${c.green}http://${addr.address}:${PORT}${c.reset}`);
            }
        }
    }

    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}掃描端點：${c.reset} POST /api/scan (NDJSON stream)`);
    if (defaultApiKey)    console.log(`${c.gray}API Key：${c.reset}  已載入（0.7 秒/次）`);
    else                  console.log(`${c.gray}API Key：${c.reset}  未設定（6.5 秒/次）`);
    if (defaultWhitelist) console.log(`${c.gray}白名單：${c.reset}   ${defaultWhitelist}`);
    console.log(`${c.gray}Log：${c.reset}      ${LOG_DIR}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}Ctrl+C 停止伺服器${c.reset}\n`);
});

server.on('error', err => {
    if (err.code === 'EADDRINUSE') {
        console.error(`\n錯誤：Port ${PORT} 已被佔用。請改用其他 Port：`);
        console.error(`  node web-server.js ${PORT + 1}\n`);
    } else {
        console.error('\n伺服器錯誤：', err.message);
    }
    process.exit(1);
});
