#!/usr/bin/env node
'use strict';

const http   = require('http');
const fs     = require('fs');
const path   = require('path');
const os     = require('os');
const crypto = require('crypto');
const { createNvdClient } = require('../lib/nvd-client');
const { findAllCPEBases } = require('../lib/cve-logic');

// ─── Port resolution ─────────────────────────────────────────────────────────
const cliPort = parseInt(process.argv[2] || '', 10);
const PORT    = (!isNaN(cliPort) && cliPort > 0 && cliPort < 65536)
                ? cliPort
                : parseInt(process.env.PORT || '8093', 10);

const { html: HTML_CONTENT, config: CONFIG } = require('./_bundle'); // auto-generated by build.js — not a taint source
const NVD_CVE_URL  = 'https://services.nvd.nist.gov/rest/json/cves/2.0';
const LOG_DIR     = path.join(__dirname, '..', 'logs');


// ─── Load .env.local (API key only — sensitive, never sent to browser) ───────
function loadEnv(filePath) {
    const env = {};
    try {
        for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
            const t = line.trim();
            if (!t || t.startsWith('#')) continue;
            const eq = t.indexOf('=');
            if (eq < 0) continue;
            env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
        }
    } catch { /* .env.local not found — skip */ }
    return env;
}

const env              = loadEnv(path.join(__dirname, '..', '.env.local'));
const defaultApiKey    = env.NIST_API_KEY || '';
// LOG_LEVEL=DEBUG 才顯示 curl 等除錯用 log（如 NVD 查詢的完整網址），平時為 INFO 不顯示
const DEBUG_LOG        = (env.LOG_LEVEL || 'INFO').toUpperCase() === 'DEBUG';

// ─── Proxy support ────────────────────────────────────────────────────────────
// require('undici') is NOT a built-in — it requires a separate npm install.
// Use Node.js built-in http+tls to tunnel HTTPS through the proxy via CONNECT.
const _proxyUrl = env.HTTPS_PROXY || env.HTTP_PROXY || process.env.HTTPS_PROXY || process.env.HTTP_PROXY || '';
const _skipTls  = (env.PROXY_SKIP_TLS_VERIFY || '').toLowerCase() === 'true';

function _makeProxyFetch(proxyUrl, skipTls) {
    const _tls  = require('tls');
    const proxy = new URL(proxyUrl);
    const proxyAuth = proxy.username
        ? 'Basic ' + Buffer.from(
            `${decodeURIComponent(proxy.username)}:${decodeURIComponent(proxy.password)}`
          ).toString('base64')
        : null;

    return function proxyFetch(urlStr, opts = {}) {
        const target = new URL(urlStr);
        const { headers: reqHeaders = {}, signal } = opts;
        return new Promise((resolve, reject) => {
            if (signal?.aborted)
                return reject(Object.assign(new Error('The operation was aborted'), { name: 'AbortError' }));

            const connectHdrs = { Host: `${target.hostname}:443` };
            if (proxyAuth) connectHdrs['Proxy-Authorization'] = proxyAuth;

            const cReq = http.request({
                host: proxy.hostname, port: +proxy.port || 80,
                method: 'CONNECT', path: `${target.hostname}:443`,
                headers: connectHdrs,
            });
            const onAbort = () => cReq.destroy(Object.assign(new Error('The operation was aborted'), { name: 'AbortError' }));
            signal?.addEventListener('abort', onAbort, { once: true });

            cReq.on('error', err => { signal?.removeEventListener('abort', onAbort); reject(err); });
            cReq.on('connect', (res, socket) => {
                signal?.removeEventListener('abort', onAbort);
                if (res.statusCode !== 200) {
                    socket.destroy();
                    return reject(new Error(`Proxy CONNECT failed: HTTP ${res.statusCode}`));
                }
                const sock = _tls.connect({
                    socket, host: target.hostname, servername: target.hostname,
                    rejectUnauthorized: !skipTls,
                });
                sock.on('error', reject);
                sock.on('secureConnect', () => {
                    const reqPath = (target.pathname || '/') + target.search;
                    const hlines  = Object.entries(reqHeaders).map(([k, v]) => `${k}: ${v}`).join('\r\n');
                    sock.write(
                        `GET ${reqPath} HTTP/1.1\r\nHost: ${target.hostname}\r\n` +
                        (hlines ? hlines + '\r\n' : '') +
                        'Connection: close\r\n\r\n'
                    );
                    const bufs = [];
                    sock.on('data', c => bufs.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
                    sock.on('end', () => {
                        try {
                            const raw    = Buffer.concat(bufs);
                            const sep    = raw.indexOf('\r\n\r\n');
                            if (sep < 0) throw new Error('Malformed HTTP response');
                            const status = parseInt(raw.slice(0, raw.indexOf('\r\n')).toString('ascii').split(' ')[1], 10);
                            const hdrs   = raw.slice(0, sep).toString('ascii').toLowerCase();
                            let   body   = raw.slice(sep + 4);
                            if (hdrs.includes('transfer-encoding: chunked')) {
                                const parts = [];
                                let pos = 0;
                                while (pos < body.length) {
                                    const nl   = body.indexOf('\r\n', pos);
                                    if (nl < 0) break;
                                    const size = parseInt(body.slice(pos, nl).toString('ascii').trim(), 16);
                                    if (!size) break;
                                    parts.push(body.slice(nl + 2, nl + 2 + size));
                                    pos = nl + 2 + size + 2;
                                }
                                body = Buffer.concat(parts);
                            }
                            const bodyStr = body.toString('utf8');
                            resolve({ ok: status >= 200 && status < 300, status, json: () => Promise.resolve(JSON.parse(bodyStr)) });
                        } catch (e) { reject(e); }
                    });
                });
            });
            cReq.end();
        });
    };
}

const _fetch = _proxyUrl ? _makeProxyFetch(_proxyUrl, _skipTls) : fetch;

// Non-sensitive config comes from config-bundle (require, not fs.readFile)
const defaultWhitelist = CONFIG.whitelist;
const REQUEST_DELAY    = CONFIG.requestDelay;
const portableEnable   = CONFIG.portableEnable;
const defaultPortables = CONFIG.portables;

// 解析 CACHE_ALIAS_N 環境變數（格式：canonical|alias1|alias2）
function _loadAliases() {
    const aliases = {};
    let i = 0;
    while (true) {
        const entry = env[`CACHE_ALIAS_${i}`];
        if (!entry) break;
        const parts = entry.split('|').map(s => s.trim().toLowerCase()).filter(Boolean);
        if (parts.length >= 2) aliases[parts[0]] = parts.slice(1);
        i++;
    }
    return aliases;
}

// ─── Daily-rolling logger ─────────────────────────────────────────────────────
fs.mkdirSync(LOG_DIR, { recursive: true });

let _logStream = null;
let _logDate   = '';

function _logDateStr() {
    const d = new Date();
    return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
}

function _logTs() {
    const d   = new Date();
    const ymd = _logDateStr();
    const hh  = String(d.getHours()).padStart(2, '0');
    const mm  = String(d.getMinutes()).padStart(2, '0');
    const ss  = String(d.getSeconds()).padStart(2, '0');
    const ms  = String(d.getMilliseconds()).padStart(3, '0');
    return `${ymd} ${hh}${mm}${ss}${ms}`;
}

function _getStream() {
    const today = _logDateStr();
    if (today !== _logDate) {
        try { _logStream?.end(); } catch (_) {}
        _logStream = fs.createWriteStream(
            path.join(LOG_DIR, `server_${today}.log`), { flags: 'a' }
        );
        _logDate = today;
    }
    return _logStream;
}

function slog(sid, msg) {
    const line = `${sid}: ${_logTs()} ${msg}`;
    console.log(line);
    try { _getStream().write(line + '\n'); } catch (_) {}
}

// ─── Session ID ───────────────────────────────────────────────────────────────
let _sessionSeq = 0;
const newSid = () => `#${String((_sessionSeq = _sessionSeq % 9999 + 1)).padStart(4, '0')}`;

// ─── Global NVD rate-limit queue ─────────────────────────────────────────────
// All concurrent sessions share this queue so combined request rate never
// exceeds REQUEST_DELAY regardless of how many users scan simultaneously.
let _nvdLastAt = 0;
let _nvdQueue  = Promise.resolve();

function nvdSlot() {
    const p = _nvdQueue.then(() => {
        const wait = Math.max(0, _nvdLastAt + REQUEST_DELAY - Date.now());
        return sleep(wait).then(() => { _nvdLastAt = Date.now(); });
    });
    _nvdQueue = p.catch(() => {});
    return p;
}

// ─── NVD Client（快取 + 120 天分段查詢）─────────────────────────────────────
// slotFn 傳入全域 nvdSlot，確保所有 session 共用同一速率限制。
// 快取存於 <project>/data/ 目錄；CACHE_DISABLE=true 可停用快取。
const _cacheDisable = (env.CACHE_DISABLE || '').toLowerCase() === 'true';
const _cacheDir     = _cacheDisable ? null : path.join(__dirname, '..', 'data');
const nvdClient     = createNvdClient({
    fetchFn:  _fetch,
    apiKey:   defaultApiKey,
    delay:    REQUEST_DELAY,
    cacheDir: _cacheDir,
    aliases:  _loadAliases(),
    slotFn:   nvdSlot,
    logger: (level, _kw, msg) => {
        if (level === 'warn') console.warn(`[nvd-client] ${msg}`);
    },
});

// ─── Page injection ───────────────────────────────────────────────────────────
// Injected before </body>: signals proxy mode and pre-fills settings.
// jsStr: JSON.stringify + escape </ so it cannot terminate the <script> block.
const jsStr = v => JSON.stringify(v).replace(/<\//g, '\\u003C/');
const injectLines = [
    `window.__NVD_PROXY__       = '/api/scan';`,
    `window.__NVD_DELAY__       = ${REQUEST_DELAY};`,
    `window.__PORTABLE_ENABLE__ = ${portableEnable};`,
];
if (portableEnable) {
    for (const p of defaultPortables) {
        injectLines.push(`if(typeof addPortableRow==='function')addPortableRow(${jsStr(p.name)},${jsStr(p.version)},${jsStr(p.publisher||'')});`);
    }
} else {
    injectLines.push(`var _ps=document.getElementById('portable-section');if(_ps)_ps.style.display='none';`);
}
if (defaultWhitelist) {
    injectLines.push(
        `var w=document.getElementById('whitelist'); if(w&&!w.value)w.value=${jsStr(defaultWhitelist)};`
    );
}
if (defaultApiKey) {
    injectLines.push(
        `var fg=document.getElementById('api-key')?.closest('.form-group');`,
        `if(fg){fg.style.display='none';var el=document.createElement('div');el.className='form-group';el.innerHTML='<label>NIST API Key</label><span class="hint" style="color:#4ade80">&#10003; 由伺服器代理處理（.env.local）</span>';fg.parentNode.insertBefore(el,fg);}`
    );
}
const makeInjectScript = n =>
    `<script nonce="${n}">(function(){\n  ${injectLines.join('\n  ')}\n})();</script>`;

// ─── Helpers ─────────────────────────────────────────────────────────────────
const sleep    = ms => new Promise(r => setTimeout(r, ms));
const readBody = req => new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', c => chunks.push(c));
    req.on('end',  () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
});

// ─── GET /api/cpe ─────────────────────────────────────────────────────────────
// Proxies NVD CPE API for web-client portable-item CPE pre-lookup.
// 改走 nvdClient.fetchCPEs()：套用相同的「同一天」快取邏輯 + 全域速率限制，
// 不再自行呼叫 nvdSlot()/_fetch（避免同一軟體當天被重複掃描時一直打 NVD CPE API）
// Usage: GET /api/cpe?keyword=PuTTY
async function cpeHandler(req, res) {
    const reqUrl  = new URL(req.url, 'http://localhost');
    const keyword = reqUrl.searchParams.get('keyword') || '';
    if (!keyword) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: 'keyword required' }));
        return;
    }
    try {
        const data = await nvdClient.fetchCPEs(keyword);
        console.log(`[CPE] ${keyword}: ${data.fromCache ? '[CPE 快取] 命中（今天已查詢過）' : '查詢完成'}`);
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify(data));
    } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// ─── GET /api/cve-data ────────────────────────────────────────────────────────
// CVE 查詢頁籤用：搜尋本機 data/ 目錄已快取的 CVE 資料（kw_*.json / cpe_*.json），
// 不會對 NVD 發出任何請求。排除 cpekw_*.json（CPE 查找快取，schema 是 {products} 不是 {cves}）。
// Usage: GET /api/cve-data?q=putty 或 ?q=CVE-2024-12345
async function cveDataHandler(req, res) {
    const reqUrl = new URL(req.url, 'http://localhost');
    const q = (reqUrl.searchParams.get('q') || '').trim();
    if (q.length < 2) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: 'q 至少需 2 個字元' }));
        return;
    }
    if (!_cacheDir) {
        // CACHE_DISABLE=true，本機沒有任何快取可查
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ results: [] }));
        return;
    }
    try {
        const qLower = q.toLowerCase();
        const qUpper = q.toUpperCase();
        let files;
        try {
            files = await fs.promises.readdir(_cacheDir);
        } catch {
            files = []; // data/ 目錄尚未建立（從未掃描過任何軟體）
        }
        const results = [];
        for (const f of files) {
            if (!f.endsWith('.json')) continue;
            let parsed;
            try {
                parsed = JSON.parse(await fs.promises.readFile(path.join(_cacheDir, f), 'utf-8'));
            } catch { continue; }
            if (!Array.isArray(parsed.cves)) continue; // 排除 cpekw_*.json
            const cacheKeyMatch = (parsed.cacheKey || '').toLowerCase().includes(qLower);
            const cveIdMatch = parsed.cves.some(v => (v.cve?.id || '').toUpperCase().includes(qUpper));
            if (cacheKeyMatch || cveIdMatch) {
                results.push({
                    cacheKey: parsed.cacheKey,
                    lastFetchedAt: parsed.lastFetchedAt,
                    coverageStart: parsed.coverageStart,
                    cveCount: parsed.cveCount,
                    cves: parsed.cves,
                });
            }
        }
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ results }));
    } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// ─── POST /api/scan ───────────────────────────────────────────────────────────
// Accepts { keywords: string[], maxCves: number, meta: object }.
// Streams NDJSON: one {"keyword","data"} line per item, then {"done":true}.
async function scanHandler(req, res) {
    const sid = newSid();
    const ip  = req.socket.remoteAddress || '?';

    let keywords, maxCves, meta, cpeMap;
    try {
        const body = await readBody(req);
        const parsed = JSON.parse(body);
        keywords = parsed.keywords;
        maxCves  = Math.max(1, parseInt(parsed.maxCves, 10) || 50);
        meta     = parsed.meta || {};
        cpeMap   = (parsed.cpeMap && typeof parsed.cpeMap === 'object') ? parsed.cpeMap : {};
        if (!Array.isArray(keywords) || keywords.length === 0)
            throw new Error('keywords must be a non-empty array');
    } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
        return;
    }

    // ── Log scan start ────────────────────────────────────────────────────────
    const total      = keywords.length;
    const portable   = meta.portableCount    || 0;
    const wl         = meta.whitelistedCount || 0;
    const skipped    = meta.skippedCount     || 0;
    const dedup      = meta.dedupCount       || 0;
    const minSev      = meta.minSeverity      || '?';
    const minYear     = meta.minYear && meta.minYear !== '?' ? Number(meta.minYear) : 0;
    const apiKeyTag   = defaultApiKey ? '已設定' : '未設定';
    const estSecs     = Math.ceil(total * REQUEST_DELAY / 1000);
    const portableTag = portable ? ` + ${portable} Portable` : '';
    const yearTag     = minYear ? String(minYear) : '不限';

    slog(sid, `▶ [${ip}] 開始掃描 ${total} 項軟體${portableTag} (白名單:${wl} 子元件:${skipped} 去重:${dedup})`);
    slog(sid, `  設定：嚴重度≥${minSev}，年份≥${yearTag}，每項最多${maxCves}筆，API Key:${apiKeyTag}，預估${estSecs}秒`);

    let cancelled = false;
    req.on('close', () => { cancelled = true; });
    res.on('error', () => {});

    res.writeHead(200, {
        'Content-Type':           'application/x-ndjson',
        'Cache-Control':          'no-cache',
        'X-Accel-Buffering':      'no',
        'X-Content-Type-Options': 'nosniff',
    });
    res.write(JSON.stringify({ sid }) + '\n');

    // 解析 minYear（來自 meta.minYear），使用 UTC 避免時區偏移
    const coverageStart = minYear
        ? new Date(Date.UTC(minYear, 0, 1))
        : new Date(Date.UTC(new Date().getUTCFullYear() - 5, 0, 1));

    let scanned = 0;
    for (let i = 0; i < keywords.length; i++) {
        if (cancelled) break;
        // 速率控制由 nvdClient 內部透過 slotFn=nvdSlot 處理，此處無需再呼叫 nvdSlot()

        const keyword = keywords[i];
        scanned++;

        try {
            // 進度 log 回調：寫入 server log 並同時以 NDJSON log 行推送給前端
            // debug 等級（如 curl 網址）僅在 LOG_LEVEL=DEBUG 時才輸出，平時略過
            const itemLog = (level, msg) => {
                if (level === 'debug' && !DEBUG_LOG) return;
                slog(sid, `  [${scanned}/${total}] ${keyword} ${msg}`);
                if (!cancelled) res.write(JSON.stringify({ keyword, log: msg, level }) + '\n');
            };

            // Portable 軟體使用前端傳來的 CPE 陣列（OR 邏輯，可能多個 vendor:product）；
            // 一般軟體先自動偵測 CPE，找不到才 fallback 至 keywordSearch。
            // CPE virtualMatchString 為索引查詢，比 keywordSearch 全文掃描更快且更穩定（降低 503）
            let cpeBases = Array.isArray(cpeMap[keyword]) ? cpeMap[keyword] : []; // Portable 由前端傳入
            if (cpeBases.length === 0) {
                let cpeData = { products: [], fromCache: false };
                try {
                    cpeData = await nvdClient.fetchCPEs(keyword);
                    const nameWords = keyword.toLowerCase().replace(/[^a-z0-9]/g, ' ').split(/\s+/).filter(w => w.length >= 2);
                    cpeBases = findAllCPEBases(cpeData.products || [], nameWords);
                } catch {}
                if (cpeBases.length > 0) {
                    const cacheTag = cpeData.fromCache
                        ? `[CPE 快取] 命中（${cpeBases.length} 筆，今天已查詢過）`
                        : `[CPE] 查詢完成（${cpeBases.length} 筆）`;
                    itemLog('cache', cacheTag);
                    itemLog('info', `自動偵測：${cpeBases.map(b => `${b.vendor}:${b.product}`).join(' | ')}`);
                }
            }

            // 找到多個 CPE base 時逐一查詢並依 CVE id 合併去重，
            // 避免只查第一個 CPE 漏掉其他 vendor 名稱下的 CVE（例如 Bruno 的 usebruno:bruno / yaxim:bruno）
            let cves, fromCache, newCount;
            if (cpeBases.length > 0) {
                const cveMap = new Map();
                fromCache = true;
                newCount  = 0;
                for (let bi = 0; bi < cpeBases.length; bi++) {
                    const base = cpeBases[bi];
                    itemLog('info', `查詢 (${bi + 1}/${cpeBases.length})CPE：cpe:2.3:a:${base.vendor}:${base.product}:*`);
                    const r = await nvdClient.fetchCVEs({
                        queryType:  'cpe',
                        queryValue: base,
                        coverageStart,
                        endDate:    new Date(),
                        log:        itemLog,
                    });
                    for (const v of r.cves) cveMap.set(v.cve.id, v);
                    fromCache = fromCache && r.fromCache;
                    newCount += r.newCount;
                }
                cves = [...cveMap.values()];
            } else {
                ({ cves, fromCache, newCount } = await nvdClient.fetchCVEs({
                    queryType:  'keyword',
                    queryValue: keyword,
                    coverageStart,
                    endDate:    new Date(),
                    log:        itemLog,
                }));
            }

            if (cancelled) break;

            const data = { vulnerabilities: cves, totalResults: cves.length, resultsPerPage: cves.length };
            const cacheTag = fromCache ? '（快取）' : `（新增 ${newCount} 筆）`;
            slog(sid, `  [${scanned}/${total}] ${keyword} — 共 ${cves.length} 筆 CVE${cacheTag}，（尚未過濾嚴重度/年份/關聯性）`);
            // cpeBases（無論來自前端或伺服器自動偵測）一併送回前端，讓前端改用 cveMatchesCPEBase 精確比對
            const ndjsonPayload = { keyword, data };
            if (cpeBases.length > 0) ndjsonPayload.cpeBases = cpeBases;
            res.write(JSON.stringify(ndjsonPayload) + '\n');

        } catch (err) {
            if (err.name === 'AbortError') break;
            slog(sid, `  [${scanned}/${total}] ${keyword} — 失敗：${err.message}`);
            res.write(JSON.stringify({ keyword, error: err.message }) + '\n');
        }
    }

    if (cancelled) {
        slog(sid, `■ [${ip}] 掃描取消（已完成 ${scanned}/${total}）`);
    } else {
        slog(sid, `✓ [${ip}] 掃描完成 ${scanned}/${total}`);
    }

    if (!cancelled) res.write(JSON.stringify({ done: true }) + '\n');
    res.end();
}

// ─── Request handler ──────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
    if (req.url === '/api/log' && req.method === 'POST') {
        readBody(req).then(body => {
            try {
                const { sid, msg } = JSON.parse(body);
                if (sid && msg) {
                    for (const line of String(msg).split('\n'))
                        slog(sid, `  ${line}`);
                }
            } catch (_) {}
            res.writeHead(204); res.end();
        }).catch(() => { res.writeHead(400); res.end(); });
        return;
    }

    if (req.url.startsWith('/api/cpe') && req.method === 'GET') {
        cpeHandler(req, res).catch(err => {
            console.error('[cpe] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.url.startsWith('/api/cve-data') && req.method === 'GET') {
        cveDataHandler(req, res).catch(err => {
            console.error('[cve-data] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.url === '/api/scan' && req.method === 'POST') {
        scanHandler(req, res).catch(err => {
            console.error('[scan] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.method !== 'GET') {
        res.writeHead(405, { 'X-Content-Type-Options': 'nosniff' }); res.end(); return;
    }


    if (req.url !== '/' && req.url !== '/index.html') {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' });
        res.end('404 Not Found');
        return;
    }

    const nonce  = crypto.randomBytes(16).toString('base64');
    const nonced = HTML_CONTENT.replace(/(<script)(?=[\s>])/i, `$1 nonce="${nonce}"`);
    const idx    = nonced.lastIndexOf('</body>');
    const html   = nonced.slice(0, idx) + makeInjectScript(nonce) + '\n' + nonced.slice(idx);
    const buf    = Buffer.from(html, 'utf8');
    const csp    = [
        "default-src 'self'",
        `script-src 'nonce-${nonce}'`,
        "style-src 'self' 'unsafe-inline'",
        "connect-src 'self' https://services.nvd.nist.gov",
        "img-src 'self' data: blob:",
        "object-src 'none'",
        "base-uri 'self'",
    ].join('; ');
    res.writeHead(200, {
        'Content-Type':            'text/html; charset=utf-8',
        'Cache-Control':           'no-store',
        'Content-Length':          buf.length,
        'X-Content-Type-Options':  'nosniff',
        'Content-Security-Policy': csp,
    });
    res.end(buf);
});

// ─── Start ────────────────────────────────────────────────────────────────────
server.keepAliveTimeout = 65000;
server.headersTimeout   = 70000;

server.listen(PORT, '0.0.0.0', () => {
    const c = { bold: '\x1b[1m', reset: '\x1b[0m', cyan: '\x1b[36m', green: '\x1b[32m', gray: '\x1b[90m' };

    console.log(`\n${c.bold}CVE Web Scanner${c.reset}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}本機：${c.reset}    ${c.cyan}http://localhost:${PORT}${c.reset}`);

    for (const addrs of Object.values(os.networkInterfaces())) {
        for (const addr of addrs) {
            if (addr.family === 'IPv4' && !addr.internal) {
                console.log(`${c.gray}區域網路：${c.reset} ${c.bold}${c.green}http://${addr.address}:${PORT}${c.reset}`);
            }
        }
    }

    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}掃描端點：${c.reset} POST /api/scan (NDJSON stream), GET /api/cpe (CPE 查找), GET /api/cve-data (CVE 查詢)`);
    if (defaultApiKey)    console.log(`${c.gray}API Key：${c.reset}  已載入（0.7 秒/次）`);
    else                  console.log(`${c.gray}API Key：${c.reset}  未設定（6.5 秒/次）`);
    if (defaultWhitelist) console.log(`${c.gray}白名單：${c.reset}   ${defaultWhitelist}`);
    console.log(`${c.gray}Log：${c.reset}      ${LOG_DIR}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}Ctrl+C 停止伺服器${c.reset}\n`);
});

server.on('error', err => {
    if (err.code === 'EADDRINUSE') {
        console.error(`\n錯誤：Port ${PORT} 已被佔用。請改用其他 Port：`);
        console.error(`  node web-server.js ${PORT + 1}\n`);
    } else {
        console.error('\n伺服器錯誤：', err.message);
    }
    process.exit(1);
});
