#!/usr/bin/env node
'use strict';

const http   = require('http');
const fs     = require('fs');
const path   = require('path');
const os     = require('os');
const crypto = require('crypto');
const { createNvdClient } = require('../lib/nvd-client');
const { createMitreClient } = require('../lib/mitre-client');
const { findAllCPEBases, isPendingSupplementCVE } = require('../lib/cve-logic');

// ─── Port resolution ─────────────────────────────────────────────────────────
const cliPort = parseInt(process.argv[2] || '', 10);
const PORT    = (!isNaN(cliPort) && cliPort > 0 && cliPort < 65536)
                ? cliPort
                : parseInt(process.env.PORT || '8093', 10);

const { html: HTML_CONTENT, config: CONFIG } = require('./_bundle'); // auto-generated by build.js — not a taint source
const NVD_CVE_URL  = 'https://services.nvd.nist.gov/rest/json/cves/2.0';
const LOG_DIR     = path.join(__dirname, '..', 'logs');


// ─── Load .env.local (API key only — sensitive, never sent to browser) ───────
function loadEnv(filePath) {
    const env = {};
    try {
        for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
            const t = line.trim();
            if (!t || t.startsWith('#')) continue;
            const eq = t.indexOf('=');
            if (eq < 0) continue;
            env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
        }
    } catch { /* .env.local not found — skip */ }
    return env;
}

const env              = loadEnv(path.join(__dirname, '..', '.env.local'));
const defaultApiKey    = env.NIST_API_KEY || '';
// LOG_LEVEL=DEBUG 才顯示 curl 等除錯用 log（如 NVD 查詢的完整網址），平時為 INFO 不顯示
const DEBUG_LOG        = (env.LOG_LEVEL || 'INFO').toUpperCase() === 'DEBUG';

// ─── Proxy support ────────────────────────────────────────────────────────────
// require('undici') is NOT a built-in — it requires a separate npm install.
// Use Node.js built-in http+tls to tunnel HTTPS through the proxy via CONNECT.
const _proxyUrl = env.HTTPS_PROXY || env.HTTP_PROXY || process.env.HTTPS_PROXY || process.env.HTTP_PROXY || '';
const _skipTls  = (env.PROXY_SKIP_TLS_VERIFY || '').toLowerCase() === 'true';

function _makeProxyFetch(proxyUrl, skipTls) {
    const _tls  = require('tls');
    const proxy = new URL(proxyUrl);
    const proxyAuth = proxy.username
        ? 'Basic ' + Buffer.from(
            `${decodeURIComponent(proxy.username)}:${decodeURIComponent(proxy.password)}`
          ).toString('base64')
        : null;

    return function proxyFetch(urlStr, opts = {}) {
        const target = new URL(urlStr);
        const { headers: reqHeaders = {}, signal } = opts;
        return new Promise((resolve, reject) => {
            if (signal?.aborted)
                return reject(Object.assign(new Error('The operation was aborted'), { name: 'AbortError' }));

            const connectHdrs = { Host: `${target.hostname}:443` };
            if (proxyAuth) connectHdrs['Proxy-Authorization'] = proxyAuth;

            const cReq = http.request({
                host: proxy.hostname, port: +proxy.port || 80,
                method: 'CONNECT', path: `${target.hostname}:443`,
                headers: connectHdrs,
            });
            const onAbort = () => cReq.destroy(Object.assign(new Error('The operation was aborted'), { name: 'AbortError' }));
            signal?.addEventListener('abort', onAbort, { once: true });

            cReq.on('error', err => { signal?.removeEventListener('abort', onAbort); reject(err); });
            cReq.on('connect', (res, socket) => {
                signal?.removeEventListener('abort', onAbort);
                if (res.statusCode !== 200) {
                    socket.destroy();
                    return reject(new Error(`Proxy CONNECT failed: HTTP ${res.statusCode}`));
                }
                const sock = _tls.connect({
                    socket, host: target.hostname, servername: target.hostname,
                    rejectUnauthorized: !skipTls,
                });
                sock.on('error', reject);
                sock.on('secureConnect', () => {
                    const reqPath = (target.pathname || '/') + target.search;
                    const hlines  = Object.entries(reqHeaders).map(([k, v]) => `${k}: ${v}`).join('\r\n');
                    sock.write(
                        `GET ${reqPath} HTTP/1.1\r\nHost: ${target.hostname}\r\n` +
                        (hlines ? hlines + '\r\n' : '') +
                        'Connection: close\r\n\r\n'
                    );
                    const bufs = [];
                    sock.on('data', c => bufs.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
                    sock.on('end', () => {
                        try {
                            const raw    = Buffer.concat(bufs);
                            const sep    = raw.indexOf('\r\n\r\n');
                            if (sep < 0) throw new Error('Malformed HTTP response');
                            const status = parseInt(raw.slice(0, raw.indexOf('\r\n')).toString('ascii').split(' ')[1], 10);
                            const hdrs   = raw.slice(0, sep).toString('ascii').toLowerCase();
                            let   body   = raw.slice(sep + 4);
                            if (hdrs.includes('transfer-encoding: chunked')) {
                                const parts = [];
                                let pos = 0;
                                while (pos < body.length) {
                                    const nl   = body.indexOf('\r\n', pos);
                                    if (nl < 0) break;
                                    const size = parseInt(body.slice(pos, nl).toString('ascii').trim(), 16);
                                    if (!size) break;
                                    parts.push(body.slice(nl + 2, nl + 2 + size));
                                    pos = nl + 2 + size + 2;
                                }
                                body = Buffer.concat(parts);
                            }
                            const bodyStr = body.toString('utf8');
                            resolve({ ok: status >= 200 && status < 300, status, json: () => Promise.resolve(JSON.parse(bodyStr)) });
                        } catch (e) { reject(e); }
                    });
                });
            });
            cReq.end();
        });
    };
}

const _fetch = _proxyUrl ? _makeProxyFetch(_proxyUrl, _skipTls) : fetch;

// Non-sensitive config comes from config-bundle (require, not fs.readFile)
const defaultWhitelist = CONFIG.whitelist;
const REQUEST_DELAY    = CONFIG.requestDelay;
const portableEnable   = CONFIG.portableEnable;
const defaultPortables = CONFIG.portables;

// 解析 CACHE_ALIAS_N 環境變數（格式：canonical|alias1|alias2）
function _loadAliases() {
    const aliases = {};
    let i = 0;
    while (true) {
        const entry = env[`CACHE_ALIAS_${i}`];
        if (!entry) break;
        const parts = entry.split('|').map(s => s.trim().toLowerCase()).filter(Boolean);
        if (parts.length >= 2) aliases[parts[0]] = parts.slice(1);
        i++;
    }
    return aliases;
}

// 解析 CPE_BASE_N 環境變數（格式：名稱|vendor:product[|vendor:product...]）。
// 通用知名軟體（Python/Git 等）預先指定標準 CPE base，跳過 CPE 字典查詢、直接精準查 CVE。
// 與 cve-checker.js 的 loadCpeBases() 一致。回傳 { 名稱(小寫): [{vendor,product}, ...] }。
function _loadCpeBases() {
    const map = {};
    let i = 0;
    while (true) {
        const entry = env[`CPE_BASE_${i}`];
        if (!entry) break;
        const parts = entry.split('|').map(s => s.trim()).filter(Boolean);
        if (parts.length >= 2) {
            const name = parts[0].toLowerCase();
            const bases = [];
            for (const vp of parts.slice(1)) {
                const [vendor, product] = vp.split(':').map(s => s.trim().toLowerCase());
                if (vendor && product) bases.push({ vendor, product });
            }
            if (bases.length) map[name] = bases;
        }
        i++;
    }
    return map;
}
const _cpeBaseMap = _loadCpeBases();

// ─── Daily-rolling logger ─────────────────────────────────────────────────────
fs.mkdirSync(LOG_DIR, { recursive: true });

let _logStream = null;
let _logDate   = '';

function _logDateStr() {
    const d = new Date();
    return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
}

function _logTs() {
    const d   = new Date();
    const ymd = _logDateStr();
    const hh  = String(d.getHours()).padStart(2, '0');
    const mm  = String(d.getMinutes()).padStart(2, '0');
    const ss  = String(d.getSeconds()).padStart(2, '0');
    const ms  = String(d.getMilliseconds()).padStart(3, '0');
    return `${ymd} ${hh}${mm}${ss}${ms}`;
}

function _getStream() {
    const today = _logDateStr();
    if (today !== _logDate) {
        try { _logStream?.end(); } catch (_) {}
        _logStream = fs.createWriteStream(
            path.join(LOG_DIR, `server_${today}.log`), { flags: 'a' }
        );
        _logDate = today;
    }
    return _logStream;
}

function slog(sid, msg) {
    const line = `${sid}: ${_logTs()} ${msg}`;
    console.log(line);
    try { _getStream().write(line + '\n'); } catch (_) {}
}

// 每個軟體查詢結束後插入一行真正的空白行（無 sid/時間戳前綴），讓 console/日誌檔閱讀時較整齊
function slogBlank() {
    console.log('');
    try { _getStream().write('\n'); } catch (_) {}
}

// ─── Session ID ───────────────────────────────────────────────────────────────
let _sessionSeq = 0;
const newSid = () => `#${String((_sessionSeq = _sessionSeq % 9999 + 1)).padStart(4, '0')}`;

// ─── 前端判斷結果 ack（讓 log 檔順序與 CLI/WebUI 一致：CPE→CVE→判斷，逐一軟體完成）──
// 問題根源：CPE/CVE 抓取進度由伺服器同步寫 log，但「是否相關／安全版本」判斷邏輯留在
// 前端（瀏覽器）計算後才以 /api/log 回傳寫 log，兩者完全不同步——若伺服器不等前端，
// 命中快取時伺服器會瞬間跑完所有軟體，前端判斷結果卻要等網路來回，導致 log 看起來像
// 「CPE/CVE 全部抓完，最後才集中判斷」。解法：伺服器送出每筆軟體的資料後，等前端把該
// 筆 keyword 的判斷結果 POST 回 /api/log（帶 keyword 欄位核對）才繼續下一筆；
// timeoutMs 是保護機制，避免前端異常（如分頁關閉）時卡住整個掃描。
const _pendingAcks = new Map(); // sid -> { keyword, resolve }
function waitForAck(sid, keyword, timeoutMs = 10000) {
    return new Promise(resolve => {
        const timer = setTimeout(() => { _pendingAcks.delete(sid); resolve(); }, timeoutMs);
        _pendingAcks.set(sid, { keyword, resolve: () => { clearTimeout(timer); _pendingAcks.delete(sid); resolve(); } });
    });
}

// ─── Global NVD rate-limit queue ─────────────────────────────────────────────
// All concurrent sessions share this queue so combined request rate never
// exceeds REQUEST_DELAY regardless of how many users scan simultaneously.
let _nvdLastAt = 0;
let _nvdQueue  = Promise.resolve();

function nvdSlot() {
    const p = _nvdQueue.then(() => {
        const wait = Math.max(0, _nvdLastAt + REQUEST_DELAY - Date.now());
        return sleep(wait).then(() => { _nvdLastAt = Date.now(); });
    });
    _nvdQueue = p.catch(() => {});
    return p;
}

// ─── CVE 來源（NIST 即時 API 或 MITRE 本機鏡像）──────────────────────────────
// slotFn 傳入全域 nvdSlot，確保所有 session 共用同一速率限制（僅 NIST 模式需要）。
// CVE_SOURCE=NIST（預設）：快取存於 <project>/data/ 目錄；CACHE_DISABLE=true 可停用快取。
// CVE_SOURCE=MITRE：讀取 data/mitre_mirror/ 本機鏡像（須先 npm run sync-mitre），
// 索引不存在時建構會立即 throw，下方 catch 會印出錯誤並中止伺服器啟動（fail-fast，不可帶壞狀態啟動）。
const CVE_SOURCE = (env.CVE_SOURCE || 'NIST').toUpperCase();
if (!['NIST', 'MITRE'].includes(CVE_SOURCE)) {
    console.error(`無效的 CVE_SOURCE="${env.CVE_SOURCE}"，僅支援 NIST 或 MITRE`);
    process.exit(1);
}

const _cacheDisable = (env.CACHE_DISABLE || '').toLowerCase() === 'true';
const _cacheDir     = _cacheDisable ? null : path.join(__dirname, '..', 'data');
const _nvdLogger = (level, _kw, msg) => {
    if (level === 'warn') console.warn(`[nvd-client] ${msg}`);
};

let nvdClient;
if (CVE_SOURCE === 'MITRE') {
    try {
        nvdClient = createMitreClient({
            mirrorDir: path.join(__dirname, '..', 'data', 'mitre_mirror'),
            logger: _nvdLogger,
        });
    } catch (e) {
        console.error(`\n${e.message}`);
        process.exit(1);
    }
} else {
    nvdClient = createNvdClient({
        fetchFn:  _fetch,
        apiKey:   defaultApiKey,
        delay:    REQUEST_DELAY,
        cacheDir: _cacheDir,
        aliases:  _loadAliases(),
        slotFn:   nvdSlot,
        logger: _nvdLogger,
    });
}

// ─── Page injection ───────────────────────────────────────────────────────────
// Injected before </body>: signals proxy mode and pre-fills settings.
// jsStr: JSON.stringify + escape </ so it cannot terminate the <script> block.
const jsStr = v => JSON.stringify(v).replace(/<\//g, '\\u003C/');
const injectLines = [
    `window.__NVD_PROXY__       = '/api/scan';`,
    `window.__NVD_DELAY__       = ${REQUEST_DELAY};`,
    `window.__PORTABLE_ENABLE__ = ${portableEnable};`,
    `window.__CPE_BASES__       = ${jsStr(_cpeBaseMap)};`,
];
if (portableEnable) {
    for (const p of defaultPortables) {
        injectLines.push(`if(typeof addPortableRow==='function')addPortableRow(${jsStr(p.name)},${jsStr(p.version)},${jsStr(p.publisher||'')});`);
    }
} else {
    injectLines.push(`var _ps=document.getElementById('portable-section');if(_ps)_ps.style.display='none';`);
}
if (defaultWhitelist) {
    injectLines.push(
        `var w=document.getElementById('whitelist'); if(w&&!w.value)w.value=${jsStr(defaultWhitelist)};`
    );
}
if (defaultApiKey) {
    injectLines.push(
        `var fg=document.getElementById('api-key')?.closest('.form-group');`,
        `if(fg){fg.style.display='none';var el=document.createElement('div');el.className='form-group';el.innerHTML='<label>NIST API Key</label><span class="hint" style="color:#4ade80">&#10003; 由伺服器代理處理（.env.local）</span>';fg.parentNode.insertBefore(el,fg);}`
    );
}
const makeInjectScript = n =>
    `<script nonce="${n}">(function(){\n  ${injectLines.join('\n  ')}\n})();</script>`;

// ─── Helpers ─────────────────────────────────────────────────────────────────
const sleep    = ms => new Promise(r => setTimeout(r, ms));
const readBody = req => new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', c => chunks.push(c));
    req.on('end',  () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
});

// ─── GET /api/cpe ─────────────────────────────────────────────────────────────
// Proxies NVD CPE API for web-client portable-item CPE pre-lookup.
// 改走 nvdClient.fetchCPEs()：套用相同的「同一天」快取邏輯 + 全域速率限制，
// 不再自行呼叫 nvdSlot()/_fetch（避免同一軟體當天被重複掃描時一直打 NVD CPE API）
// Usage: GET /api/cpe?keyword=PuTTY
async function cpeHandler(req, res) {
    const reqUrl  = new URL(req.url, 'http://localhost');
    const keyword = reqUrl.searchParams.get('keyword') || '';
    if (!keyword) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: 'keyword required' }));
        return;
    }
    try {
        const data = await nvdClient.fetchCPEs(keyword);
        console.log(`[CPE] ${keyword}: ${data.fromCache ? '[CPE 快取] 命中（今天已查詢過）' : '查詢完成'}`);
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify(data));
    } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// ─── GET /api/cve-data ────────────────────────────────────────────────────────
// CVE 查詢頁籤用：搜尋本機 data/cve_cache/ 目錄已快取的 CVE 資料（kw_*.json / cpe_*.json），
// 不會對 NVD 發出任何請求。CPE 字典查找快取（cpekw_*.json，schema 是 {products} 不是 {cves}）
// 另存於 data/cpe_cache/，不在此目錄下，故不需額外排除。
// Usage: GET /api/cve-data?q=putty 或 ?q=CVE-2024-12345
async function cveDataHandler(req, res) {
    const reqUrl = new URL(req.url, 'http://localhost');
    const q = (reqUrl.searchParams.get('q') || '').trim();
    if (q.length < 2) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: 'q 至少需 2 個字元' }));
        return;
    }
    if (!_cacheDir) {
        // CACHE_DISABLE=true，本機沒有任何快取可查
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ results: [] }));
        return;
    }
    const cveCacheDir = path.join(_cacheDir, 'cve_cache');
    try {
        const qLower = q.toLowerCase();
        const qUpper = q.toUpperCase();
        let files;
        try {
            files = await fs.promises.readdir(cveCacheDir);
        } catch {
            files = []; // data/cve_cache/ 目錄尚未建立（從未掃描過任何軟體）
        }
        const results = [];
        for (const f of files) {
            if (!f.endsWith('.json')) continue;
            let parsed;
            try {
                parsed = JSON.parse(await fs.promises.readFile(path.join(cveCacheDir, f), 'utf-8'));
            } catch { continue; }
            if (!Array.isArray(parsed.cves)) continue;
            const cacheKeyMatch = (parsed.cacheKey || '').toLowerCase().includes(qLower);
            const cveIdMatch = parsed.cves.some(v => (v.cve?.id || '').toUpperCase().includes(qUpper));
            if (cacheKeyMatch || cveIdMatch) {
                results.push({
                    cacheKey: parsed.cacheKey,
                    lastFetchedAt: parsed.lastFetchedAt,
                    coverageStart: parsed.coverageStart,
                    cveCount: parsed.cveCount,
                    cves: parsed.cves,
                });
            }
        }
        res.writeHead(200, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ results }));
    } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// ─── POST /api/scan ───────────────────────────────────────────────────────────
// Accepts { keywords: string[], maxCves: number, meta: object, names: object }.
// Streams NDJSON: one {"keyword","data"} line per item, then {"done":true}.
async function scanHandler(req, res) {
    const sid = newSid();
    const ip  = req.socket.remoteAddress || '?';

    let keywords, maxCves, meta, names, portables;
    try {
        const body = await readBody(req);
        const parsed = JSON.parse(body);
        keywords = parsed.keywords;
        maxCves  = Math.max(1, parseInt(parsed.maxCves, 10) || 50);
        meta     = parsed.meta || {};
        // searchName → { name, version }，僅供 log 顯示用（伺服器查詢一律以 keyword 為準）
        names     = (parsed.names && typeof parsed.names === 'object') ? parsed.names : {};
        // 哪些 searchName 是 Portable 軟體：CPE 偵測流程與一般軟體相同（皆由 server 自動偵測），
        // 只是顯示用語不同——與 CLI 一致：Portable 找不到 CPE 顯示 ⚠ 警告，且不顯示「（自動偵測）」標籤
        portables = new Set(Array.isArray(parsed.portables) ? parsed.portables : []);
        if (!Array.isArray(keywords) || keywords.length === 0)
            throw new Error('keywords must be a non-empty array');
    } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' });
        res.end(JSON.stringify({ error: err.message }));
        return;
    }

    // ── Log scan start ────────────────────────────────────────────────────────
    const total      = keywords.length;
    const portable   = meta.portableCount    || 0;
    const wl         = meta.whitelistedCount || 0;
    const skipped    = meta.skippedCount     || 0;
    const dedup      = meta.dedupCount       || 0;
    const minSev      = meta.minSeverity      || '?';
    const minYear     = meta.minYear && meta.minYear !== '?' ? Number(meta.minYear) : 0;
    const apiKeyTag   = defaultApiKey ? '已設定' : '未設定';
    const estSecs     = Math.ceil(total * REQUEST_DELAY / 1000);
    const portableTag = portable ? ` + ${portable} Portable` : '';
    const yearTag     = minYear ? String(minYear) : '不限';

    slog(sid, `▶ [${ip}] 開始掃描 ${total} 項軟體${portableTag} (白名單:${wl} 子元件:${skipped} 去重:${dedup})`);
    slog(sid, `  設定：嚴重度≥${minSev}，年份≥${yearTag}，API Key:${apiKeyTag}，預估${estSecs}秒`);

    let cancelled = false;
    req.on('close', () => {
        cancelled = true;
        _pendingAcks.get(sid)?.resolve(); // 連線中斷時立即解除等待，不要卡滿 timeout
    });
    res.on('error', () => {});

    res.writeHead(200, {
        'Content-Type':           'application/x-ndjson',
        'Cache-Control':          'no-cache',
        'X-Accel-Buffering':      'no',
        'X-Content-Type-Options': 'nosniff',
    });
    res.write(JSON.stringify({ sid }) + '\n');

    // 解析 minYear（來自 meta.minYear），使用 UTC 避免時區偏移
    const coverageStart = minYear
        ? new Date(Date.UTC(minYear, 0, 1))
        : new Date(Date.UTC(new Date().getUTCFullYear() - 1, 0, 1));

    let scanned = 0;
    for (let i = 0; i < keywords.length; i++) {
        if (cancelled) break;
        // 速率控制由 nvdClient 內部透過 slotFn=nvdSlot 處理，此處無需再呼叫 nvdSlot()

        const keyword = keywords[i];
        scanned++;

        // 與 CLI 一致：先印標頭（軟體名稱/版本 + search 行），再印 CPE/快取等過程訊息，
        // 不能等到最終結果回來才印——否則標頭會排在過程訊息之後，順序與 CLI 顛倒
        const swName = names[keyword] || {};
        slog(sid, `  [${scanned}/${total}] ${swName.name || keyword} v${swName.version || '?'}`);
        slog(sid, `  [${scanned}/${total}]   search: "${keyword}"`);
        if (!cancelled) {
            res.write(JSON.stringify({ keyword, header: { name: swName.name || keyword, version: swName.version || '?' } }) + '\n');
        }

        try {
            // 進度 log 回調：寫入 server log 並同時以 NDJSON log 行推送給前端
            // debug 等級（如 curl 網址）僅在 LOG_LEVEL=DEBUG 時才輸出，平時略過
            const itemLog = (level, msg) => {
                if (level === 'debug' && !DEBUG_LOG) return;
                slog(sid, `  [${scanned}/${total}] ${msg}`);
                if (!cancelled) res.write(JSON.stringify({ keyword, log: msg, level }) + '\n');
            };

            // 所有軟體（含 Portable）都先嘗試 CPE 查詢，與 CLI 一致：CPE virtualMatchString 為索引查詢，
            // 比 keywordSearch 全文掃描更快、更準確。Portable 只是顯示用語不同（不顯示「自動偵測」標籤，
            // 找不到 CPE 時顯示 ⚠ 警告），偵測流程本身完全相同。
            const isPortable = portables.has(keyword);
            let cpeData = { products: [], fromCache: false };
            let cpeBases = [];
            const knownBases = _cpeBaseMap[keyword.toLowerCase()];
            if (knownBases) {
                // .env.local 指定的標準 CPE base（通用知名軟體）→ 跳過字典查詢，直接精準查
                cpeBases = knownBases;
                itemLog('cache', `[CPE 指定] 使用 .env.local 設定的標準 CPE（${cpeBases.length} 筆，略過字典查詢）`);
                itemLog('info', cpeBases.map(b => `cpe:2.3:a:${b.vendor}:${b.product}:*`).join(' | '));
            } else {
            try {
                cpeData = await nvdClient.fetchCPEs(keyword);
                const nameWords = keyword.toLowerCase().replace(/[^a-z0-9]/g, ' ').split(/\s+/).filter(w => w.length >= 2);
                cpeBases = findAllCPEBases(cpeData.products || [], nameWords);
            } catch {}
            if (cpeBases.length > 0) {
                const cacheTag = cpeData.fromCache
                    ? `[CPE 快取] 命中（${cpeBases.length} 筆，今天已查詢過）`
                    : `[CPE] 查詢完成（${cpeBases.length} 筆）`;
                itemLog('cache', cacheTag);
                itemLog('info', cpeBases.map(b => `cpe:2.3:a:${b.vendor}:${b.product}:*`).join(' | '));
            } else if (cpeData && cpeData.tooGeneric) {
                itemLog('info', `關鍵字過於通用（命中 ${cpeData.totalResults} 筆 CPE），改用關鍵字搜尋`);
            } else if (isPortable) {
                itemLog('warn', '⚠ 未找到對應 CPE，改用關鍵字比對');
            } else {
                itemLog('info', '未找到對應 CPE，使用關鍵字搜尋');
            }
            }

            // 找到多個 CPE base 時逐一查詢並依 CVE id 合併去重，
            // 避免只查第一個 CPE 漏掉其他 vendor 名稱下的 CVE（例如 Bruno 的 usebruno:bruno / yaxim:bruno）
            let cves, fromCache, newCount;
            if (cpeBases.length > 0) {
                const cveMap = new Map();
                fromCache = true;
                newCount  = 0;
                for (let bi = 0; bi < cpeBases.length; bi++) {
                    const base = cpeBases[bi];
                    itemLog('info', `查詢 (${bi + 1}/${cpeBases.length}) cpe:2.3:a:${base.vendor}:${base.product}:*`);
                    const r = await nvdClient.fetchCVEs({
                        queryType:  'cpe',
                        queryValue: base,
                        coverageStart,
                        endDate:    new Date(),
                        log:        itemLog,
                    });
                    for (const v of r.cves) cveMap.set(v.cve.id, v);
                    fromCache = fromCache && r.fromCache;
                    newCount += r.newCount;
                }
                // 補撈：CPE 查詢漏掉 NVD 尚未分析（Awaiting Analysis、無 CPE 適用性）的新 CVE
                // （例：FFmpeg CVE-2026-8461）。同範圍 keyword 查詢補回「無 CPE 且參考連結指向本
                // 軟體」者，後續前端 relevance 會標 _pendingNvd（⚠ NVD 分析中）。與 CLI 一致。
                const rkw = await nvdClient.fetchCVEs({
                    queryType:  'keyword',
                    queryValue: keyword,
                    coverageStart,
                    endDate:    new Date(),
                    log:        itemLog,
                });
                fromCache = fromCache && rkw.fromCache;
                newCount += rkw.newCount;
                let suppCount = 0;
                for (const v of rkw.cves) {
                    if (cveMap.has(v.cve.id)) continue;
                    if (isPendingSupplementCVE(v.cve, cpeBases)) { cveMap.set(v.cve.id, v); suppCount++; }
                }
                if (suppCount > 0) {
                    itemLog('info', `關鍵字補撈：新增 ${suppCount} 筆 NVD 尚未分析（無 CPE 適用性）的 CVE，待人工確認`);
                }
                cves = [...cveMap.values()];
            } else {
                ({ cves, fromCache, newCount } = await nvdClient.fetchCVEs({
                    queryType:  'keyword',
                    queryValue: keyword,
                    coverageStart,
                    endDate:    new Date(),
                    log:        itemLog,
                }));
            }

            if (cancelled) break;

            const data = { vulnerabilities: cves, totalResults: cves.length, resultsPerPage: cves.length };
            const cacheTag = fromCache ? '（快取）' : `（新增 ${newCount} 筆）`;
            slog(sid, `  [${scanned}/${total}] 共 ${cves.length} 筆 CVE${cacheTag}，（尚未過濾嚴重度/年份/關聯性）`);
            // cpeBases（無論來自前端或伺服器自動偵測）一併送回前端，讓前端改用 cveMatchesCPEBase 精確比對
            const ndjsonPayload = { keyword, data };
            if (cpeBases.length > 0) ndjsonPayload.cpeBases = cpeBases;
            res.write(JSON.stringify(ndjsonPayload) + '\n');
            if (!cancelled) await waitForAck(sid, keyword);

        } catch (err) {
            if (err.name === 'AbortError') break;
            slog(sid, `  [${scanned}/${total}] 失敗：${err.message}`);
            res.write(JSON.stringify({ keyword, error: err.message }) + '\n');
            if (!cancelled) await waitForAck(sid, keyword);
        }
    }

    if (cancelled) {
        slog(sid, `■ [${ip}] 掃描取消（已完成 ${scanned}/${total}）`);
    } else {
        slog(sid, `✓ [${ip}] 掃描完成 ${scanned}/${total}`);
    }

    if (!cancelled) res.write(JSON.stringify({ done: true }) + '\n');
    res.end();
}

// ─── Request handler ──────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
    if (req.url === '/api/log' && req.method === 'POST') {
        readBody(req).then(body => {
            try {
                const { sid, msg, keyword } = JSON.parse(body);
                if (sid && msg) {
                    // 空字串行代表前端標記「此軟體區塊結束」，印出真正空白行（無 sid/時間戳前綴）分隔
                    for (const line of String(msg).split('\n')) {
                        if (line === '') slogBlank();
                        else slog(sid, `  ${line}`);
                    }
                }
                // 帶 keyword 表示這是某筆軟體的判斷結果回傳，通知 scanHandler 解除等待、繼續下一筆
                // （核對 keyword 避免「掃描完成」「使用者下載報表」等其他 /api/log 呼叫誤觸發 ack）
                if (sid && keyword) {
                    const pending = _pendingAcks.get(sid);
                    if (pending && pending.keyword === keyword) pending.resolve();
                }
            } catch (_) {}
            res.writeHead(204); res.end();
        }).catch(() => { res.writeHead(400); res.end(); });
        return;
    }

    if (req.url.startsWith('/api/cpe') && req.method === 'GET') {
        cpeHandler(req, res).catch(err => {
            console.error('[cpe] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.url.startsWith('/api/cve-data') && req.method === 'GET') {
        cveDataHandler(req, res).catch(err => {
            console.error('[cve-data] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.url === '/api/scan' && req.method === 'POST') {
        scanHandler(req, res).catch(err => {
            console.error('[scan] unexpected error:', err.message);
            if (!res.headersSent) { res.writeHead(500); res.end(JSON.stringify({ error: err.message })); }
            else { try { res.end(); } catch (_) {} }
        });
        return;
    }

    if (req.method !== 'GET') {
        res.writeHead(405, { 'X-Content-Type-Options': 'nosniff' }); res.end(); return;
    }


    if (req.url !== '/' && req.url !== '/index.html') {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' });
        res.end('404 Not Found');
        return;
    }

    const nonce  = crypto.randomBytes(16).toString('base64');
    const nonced = HTML_CONTENT.replace(/(<script)(?=[\s>])/i, `$1 nonce="${nonce}"`);
    const idx    = nonced.lastIndexOf('</body>');
    const html   = nonced.slice(0, idx) + makeInjectScript(nonce) + '\n' + nonced.slice(idx);
    const buf    = Buffer.from(html, 'utf8');
    const csp    = [
        "default-src 'self'",
        `script-src 'nonce-${nonce}'`,
        "style-src 'self' 'unsafe-inline'",
        "connect-src 'self' https://services.nvd.nist.gov",
        "img-src 'self' data: blob:",
        "object-src 'none'",
        "base-uri 'self'",
    ].join('; ');
    res.writeHead(200, {
        'Content-Type':            'text/html; charset=utf-8',
        'Cache-Control':           'no-store',
        'Content-Length':          buf.length,
        'X-Content-Type-Options':  'nosniff',
        'Content-Security-Policy': csp,
    });
    res.end(buf);
});

// ─── Start ────────────────────────────────────────────────────────────────────
server.keepAliveTimeout = 65000;
server.headersTimeout   = 70000;

server.listen(PORT, '0.0.0.0', () => {
    const c = { bold: '\x1b[1m', reset: '\x1b[0m', cyan: '\x1b[36m', green: '\x1b[32m', gray: '\x1b[90m' };

    console.log(`\n${c.bold}CVE Web Scanner${c.reset}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}本機：${c.reset}    ${c.cyan}http://localhost:${PORT}${c.reset}`);

    for (const addrs of Object.values(os.networkInterfaces())) {
        for (const addr of addrs) {
            if (addr.family === 'IPv4' && !addr.internal) {
                console.log(`${c.gray}區域網路：${c.reset} ${c.bold}${c.green}http://${addr.address}:${PORT}${c.reset}`);
            }
        }
    }

    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}掃描端點：${c.reset} POST /api/scan (NDJSON stream), GET /api/cpe (CPE 查找), GET /api/cve-data (CVE 查詢)`);
    console.log(`${c.gray}CVE 來源：${c.reset} ${c.cyan}${CVE_SOURCE}${c.reset}`);
    if (defaultApiKey)    console.log(`${c.gray}API Key：${c.reset}  已載入（0.7 秒/次）`);
    else                  console.log(`${c.gray}API Key：${c.reset}  未設定（6.5 秒/次）`);
    if (defaultWhitelist) console.log(`${c.gray}白名單：${c.reset}   ${defaultWhitelist}`);
    console.log(`${c.gray}Log：${c.reset}      ${LOG_DIR}`);
    console.log(`${c.gray}${'─'.repeat(40)}${c.reset}`);
    console.log(`${c.gray}Ctrl+C 停止伺服器${c.reset}\n`);
});

server.on('error', err => {
    if (err.code === 'EADDRINUSE') {
        console.error(`\n錯誤：Port ${PORT} 已被佔用。請改用其他 Port：`);
        console.error(`  node web-server.js ${PORT + 1}\n`);
    } else {
        console.error('\n伺服器錯誤：', err.message);
    }
    process.exit(1);
});
